### ISSUE TITLE
Q: What's the effective deprecation date?

### ISSUE THREAD

**Issue by sandrooco** [SchweizerischeBundesbahnen/esta-webjs-extensions#64]
> At a later date the old npm package will be deprecated and this repository removed.

At what date will this repository be deleted/unavailable?
Would be good to know so we can start to plan the migration to the new one.

Thanks!

**Comment by kyubisation** [comment]
I'm currently on holidays, so this reply will be short.
We are in no hurry to delete this repository. We might however archive it.
As for the NPM package esta-webjs-extensions, we will deprecate that sometime after the release of Angular 9.
What is your use case/project?

**Comment by sandrooco** [comment]
We're working on quite a large project.
So we need to know the point of time when we should be migrated.

**Comment by kyubisation** [comment]
The reason for the deprecation is the migration of the code to the monorepo SchweizerischeBundesbahnen/sbb-angular. This means the repo/package esta-webjs-extensions will no longer receive any update.
In order to properly communicate this to consumers, package deprecation is the only reliable way.
The deprecation of a package will not make it unusable. You will simply have a warning in your console during dependency installation.
As for the time window for the deprecation; Angular 9 is expected to land somewhere in november. The package deprecation will be done sometime after that.

**Comment by sandrooco** [comment]
Okay, we'll try to migrate soon. Thanks.
